spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/db1?useSSL=false&charaterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    druid:
      initial-size: 5
      filters: stat,wall,slf4j
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-connect-error-millis: 60000
      test-on-return: false
      test-on-borrow: false
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      filter:
          stat:
            log-slow-sql: true
beetlsql:
  basePackage: com.liuzhoustell.dao
  dbStyle: org.beetl.sql.core.db.MySqlStyle
beetl-beetlsql:
  dev: true
